services:
  mysqldb:
    image: mysql-image
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=sys2
      - MYSQL_USER=jisun
      - MYSQL_PASSWORD=1234
    ports:
      - "3308:3306"
    volumes:
      - mysql-compose-volumes:/var/lib/mysql

volumes:
  mysql-compose-volumes:
